### ISSUE TITLE
Missing dependency: gnome-icon-theme-full 

### ISSUE THREAD

**Issue by hadbabits** [danielgtaylor/arista#147]
I'm using Linux Mint 14 KDE. I experience the bug in https://github.com/danielgtaylor/arista/issues/109

As mentioned in the thread, it can be solved by installing the gnome-icon-theme-full, but the bug is fairly old, why isn't this fixed yet?

Otherwise a great application.

**Comment by danielgtaylor** [comment]
This is definitely a packaging and dependency bug. Can you file an upstream bug on Launchpad.net for Ubuntu so that their packaging teams fix the issue? I do not maintain the .deb packages (and was encouraged not to).

Edit: You can also file them against Linux Mint, but ultimately the problem should be solved lower at the Ubuntu level, which is where Mint gets its packages.

**Comment by hadbabits** [comment]
Ok, thanks. I'm not actually a developer, and I'm new to Linux, so I didn't really know where to go, haha. Thanks for the reply!

**Comment by danielgtaylor** [comment]
Oh sorry, try the "File bug" link on the right side here:

https://launchpad.net/ubuntu/+source/arista

Feel free to link to this bug and #109 and they should be able to fix the package dependencies.

**Comment by hadbabits** [comment]
I looked on the bugs page and it appears there's already one posted for this problem (https://bugs.launchpad.net/ubuntu/+source/arista/+bug/867822) and a duplicate (https://bugs.launchpad.net/ubuntu/+source/arista/+bug/875772). The solution to the bug has been on both of them for over a year, sitting under the comments.

**Comment by danielgtaylor** [comment]
Interesting. It looks like the latest package (0.9.7-4 from https://launchpad.net/ubuntu/+source/arista ) was built by:

Alessio Treglia alessio@debian.org  Wed, 21 Mar 2012 13:41:02 +0100

Maybe try shooting him an email and pointing him to this bug. I believe he is the package maintainer. Getting him to fix it would mean it will be fixed in Debian, Ubuntu, and Mint, plus any other distros that base off of Debian.

**Comment by hadbabits** [comment]
I sent the e-mail, I'll let you know when I get a response.

**Comment by hadbabits** [comment]
No reply yet, but after searching through Debian's packages I found out it doesn't have the gnome-icon-theme-full package in it's repositories, which may be part of the problem.

**Comment by danielgtaylor** [comment]
Interesting... for what it's worth I think 8dcfd72de13a0154a723213630d822cdee6cea83 from a year ago may have fixed the issue for distros that don't have that package or those files anywhere.

I'll put it on my todo for another point release in the near future so that distros pick it up. I'll take another look over the bug list as well before then.

**Comment by hadbabits** [comment]
Alright, well thanks for the responsive help. I've always heard good things about open source devs; though I was still a bit surprised, haha.
