### ISSUE TITLE
Web Device

### ISSUE THREAD

**Issue by fcsonline** [danielgtaylor/arista#5]
Another idea.

It would be nice to create a device such as 'Web' with which to convert the videos to web format and have presets like 'Webm', 'FLV', 'OGG'.

What do you think?

**Comment by danielgtaylor** [comment]
This is a good idea. I had wanted to do something similar a while back and just never got around to it. Currently outputting to WebM requires Collabora's GStreamer trunk from git so that won't be available for most people for a while yet. H.264 also should be added to the list.

How about a device called 'Web' with the following:
- Legacy Flash (FLV)
- H.264 (H.264/AAC in MP4)
- Ogg (Theora/Vorbis in Ogg)

Then later we can add:
- WebM (VP8/Vorbis in WebM)

Pretty soon if I have some time I'd like to add detecting which components are installed on the fly and only showing presets that have all the required components installed. Then we could just put the WebM one in there and not worry about users having or not having the GStreamer plugins. Thoughts?

**Comment by fcsonline** [comment]
Just what I was thinking.

If you want, we can create a fork, to implement all the 'Web' device, and I could implement part of it.

**Comment by danielgtaylor** [comment]
Feel free to fork and start working on it. If you want to just start setting up the device profiles you don't even need to fork, just realize that I changed the format to JSON recently as it's significantly easier to process than XML, but the data itself is the same. You can use http://www.transcoder.org/presets/create/ to help out with generating the JSON, though obviously it's not enough to create what we want here, just a starting point.

In terms of auto-discovery of installed elements, I have no clue how to do that yet and will need to read up on it a bit.

**Comment by danielgtaylor** [comment]
I merged your branch and have updated the presets. Closing issue.
