### ISSUE TITLE
choose which title from DVD to rip

### ISSUE THREAD

**Issue by ghost** [danielgtaylor/arista#57]
hello

Unless, I'm missing something, I can't see a way to choose which title from a DVD (or DVD ISO file) for ripping. While in the majority of cases, a DVD is a movie, and so choosing the longest title makes sense, this does pose a problem for DVDs other than movies: TV series box sets, artist music video anthologies, animation shorts films, etc.

**Comment by Hooloovoo** [comment]
Thoggen (http://www.thoggen.net/) has a really good interface for this. It would be great if Arista could replicate this interface for DVD sources.

**Comment by ghost** [comment]
Thoggen title selection is not bad, but it could do with some helper controls for selecting/deselecting all. The option to merge titles into one encode would be handy, if probably an edge case.

**Comment by Hooloovoo** [comment]
Any reason that this was closed without comment? It is quite an important issue for me.

**Comment by ghost** [comment]
I had no idea this had been closed. It's a shame, but I can only assume it's === to WONTFIX. 

If the app can read from a DVD, reading from a DVD .iso doesn't seem that unreasonable a request. Like you, I also rip to an .iso and then transcode to: iPhone, iPad, ATV from there. I have the space to keep the .iso around, and my kid frequently wrecks the DVD discs. If any devs are reading, that's another use case for you, if the original use cases were not enough.

**Comment by supine** [comment]
I'm a Thoggen user looking for a replacement to transcode into VP8/Vorbis/WebM and Arista has only three missing features one of which is the ability to select individual chapters. Most of our DVDs contain multiple episodes, not a single movie, so in order to use Arista I would have to transfer the chapters from the DVD into individual container files. Obviously a single step process would be preferable. Handbrake has similar functionality although I prefer Thoggen's approach even if it could be improved as well.
