### ISSUE TITLE
How to fix in 4.4 GB a  6.6 GB HD BDRip movie

### ISSUE THREAD

**Issue by te-con-miel** [danielgtaylor/arista#84]
Hello,

I need to shrink a 6.6 GB .mkv HD movie (h264+aac) in 4.4 GB DVD disc, same codecs, the container can be mp4 or mkv. 

Can you help me please? 

I can not find the way to create a preset to do it. I see the presets are based on quantizers to determine diffrent video qualities but are not based on file sizes.

My intention is burn 4.7 DVDs with BDRip HD movies, generaly 6,7 or 8 GB.

Also, there is a bug when I try to convert HD BDRip to Divx, the program crash every time.

Thanks in advance.

**Comment by danielgtaylor** [comment]
You can modify the preset by hand or use Arista from git as I now have preset editing in the app. Either way you would set the video codec options to something like "bitrate=XXX" (where XXX is in kbps for x264enc) instead of the quality/quantizer setting. The presets are simple JSON files so you can edit with a text editor like gedit.

Filesize in MiB = video duration in seconds \* kbps \* 8 / 1024 / 1024
