### ISSUE TITLE
convert video without presets or create new preset without internet connection

### ISSUE THREAD

**Issue by imgxx** [danielgtaylor/arista#87]

**Comment by danielgtaylor** [comment]
This is in the works, but I've been waiting on upstream changes to get to most people before trying to implement this. The way GStreamer handles encoding is changing and I'd like to only implement this once.

Should it not be easily doable in the near future I may take another stab at it my way since we've been waiting for so long already.

**Comment by danielgtaylor** [comment]
I've taken another stab at this. You can now edit presets in Arista itself as of a few minutes ago. I'm working on being able to add new presets and rename the shortname (which is fairly complicated).
